name: Ethereum Analysis

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_LOG_LEVEL: error
  scan-contracts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      discussions: write
      pull-requests: write
      statuses: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      id: slither
      with:
        sarif: results.sarif
        fail-on: medium
        target: "contracts/"
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}